### ISSUE TITLE
Dynamic array arguments are serialized incorrectly

### ISSUE THREAD

**Issue by niran** [axic/ethereumjs-abi#6]
It looks like [the algorithm for nested dynamic arrays](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI) got confused with the one for normal dynamic arrays. A normal dynamic array (`bool[]`) only needs the length of the array to know where the array ends. A nested dynamic array (`bool[][3]`, an array of three dynamic arrays of booleans) needs to know the offsets of the three dynamic arrays so the arrays can be indexed without iterating through the dynamic arrays, so the offset of each dynamic array is packed together at the front of the encoded bytes. 

To access the second of the three dynamic arrays, you look up the second offset (the second `uint256` of the encoded value) and use that as the offset from the beginning. There, you'll find the length of the second dynamic array followed by the values, just like a non-nested dynamic array.

web3.js also has this bug: ethereum/web3.js#378

**Comment by axic** [comment]
@niran I'll wait for the decision in web3.js about the issue.

**Comment by niran** [comment]
Oops, I was wrong
